services:
  - type: web
    name: music-cat
    env: python
    plan: starter  # starter プランを利用
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --timeout=180
    healthCheckPath: /health
    autoDeploy: true
